import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/layout/Header"; // Import Header
import Footer from "@/components/layout/Footer"; // Import Footer
import BackToTop from "@/components/ui/BackToTop"; // Import BackToTop
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  // title: "Create Next App", // Remove duplicate
  // description: "Generated by create next app", // Remove duplicate
  title: "RS Airan Raya (Dev)", // Keep updated title
  description: "Website Profil RS Airan Raya - Pengembangan Awal", // Keep updated description
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`} // Add flex classes
      >
        <Header /> {/* Add Header */}
        <main className="flex-grow"> {/* Remove container styles since pages handle their own layout */}
          {children}
        </main>
        <Footer /> {/* Add Footer */}
        <BackToTop /> {/* Add BackToTop button */}
      </body>
    </html>
  );
}
